openapi: 3.0.3
info:
  title: API de Tienda Sol
  version: 1.0.2
  description: API para gestión de pedidos, productos y notificaciones

servers:
  - url: http://localhost:3000
    description: Servidor local

tags:
  - name: Pedidos
    description: Endpoints para gestión de pedidos
  - name: Productos
    description: Endpoints para gestión de productos
  - name: Notificaciones
    description: Endpoints para gestión de notificaciones

paths:
  ############################
  # PEDIDOS
  ############################
  /pedidos:
    post:
      summary: Crear un pedido
      tags: [Pedidos]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PedidoCrear'
      responses:
        '201':
          description: Pedido creado con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  pedidoId: { type: string }

    get:
      summary: Obtener todos los pedidos
      tags: [Pedidos]
      responses:
        '200':
          description: Lista de pedidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pedido'

  /pedidos/usuario/{usuarioId}:
    get:
      summary: Obtener pedidos de un usuario
      tags: [Pedidos]
      parameters:
        - in: path
          name: usuarioId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de pedidos del usuario
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PedidoResumido'

  /pedidos/{pedidoId}/cancelar:
    patch:
      summary: Cancelar un pedido
      tags: [Pedidos]
      parameters:
        - in: path
          name: pedidoId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                compradorId:
                  type: string
      responses:
        '200':
          description: Pedido cancelado con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  pedido:
                    $ref: '#/components/schemas/Pedido'
        '400':
          description: Error de negocio
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }

  /pedidos/{pedidoId}/enviar:
    patch:
      summary: Marcar pedido como enviado
      tags: [Pedidos]
      parameters:
        - in: path
          name: pedidoId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                vendedorId:
                  type: string
      responses:
        '200':
          description: Pedido marcado como enviado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  pedido:
                    $ref: '#/components/schemas/Pedido'
        '400':
          description: "No se puede enviar el pedido (ej: cancelado)"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }

  ############################
  # PRODUCTOS
  ############################
  /productos:
    post:
      summary: Crear un producto
      tags: [Productos]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ProductoCrear' }
      responses:
        '201':
          description: Producto creado con éxito
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Producto' }

    get:
      summary: Listar productos
      tags: [Productos]
      parameters:
        - name: page
          in: query
          schema: { type: integer }
        - name: limit
          in: query
          schema: { type: integer }
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Producto' }

  /productos/vendedor/{vendedorId}:
    get:
      summary: Listar productos de un vendedor con filtros y paginación
      tags: [Productos]
      parameters:
        - in: path
          name: vendedorId
          required: true
          schema: { type: string }
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, default: 10 }
        - in: query
          name: nombre
          schema: { type: string }
        - in: query
          name: descripcion
          schema: { type: string }
        - in: query
          name: categoria
          schema: { type: string }
        - in: query
          name: precioMin
          schema: { type: number }
        - in: query
          name: precioMax
          schema: { type: number }
      responses:
        '200':
          description: Lista de productos filtrados
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagina: { type: integer }
                  perPage: { type: integer }
                  total: { type: integer }
                  totalPaginas: { type: integer }
                  data:
                    type: array
                    items: { $ref: '#/components/schemas/Producto' }

  /productos/{id}:
    put:
      summary: Actualizar un producto existente
      tags: [Productos]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductoCrear'
      responses:
        '200':
          description: Producto actualizado correctamente
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Producto' }
        '404':
          description: Producto no encontrado
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }

    delete:
      summary: Eliminar producto
      tags: [Productos]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Producto eliminado correctamente
        '404':
          description: Producto no encontrado

  ############################
  # NOTIFICACIONES
  ############################
  /notificaciones/unread/{usuarioId}:
    get:
      summary: Obtener notificaciones sin leer
      tags: [Notificaciones]
      parameters:
        - in: path
          name: usuarioId
          required: true
          schema: { type: string }
        - in: query
          name: page
          schema: { type: integer, minimum: 1, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 100, default: 10 }
      responses:
        '200':
          description: Lista paginada de notificaciones sin leer
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagina: { type: integer }
                  perPage: { type: integer }
                  totalColecciones: { type: integer }
                  totalPaginas: { type: integer }
                  data:
                    type: array
                    items: { $ref: '#/components/schemas/Notificacion' }

  /notificaciones/read/{usuarioId}:
    get:
      summary: Obtener notificaciones leídas
      tags: [Notificaciones]
      parameters:
        - in: path
          name: usuarioId
          required: true
          schema: { type: string }
        - in: query
          name: page
          schema: { type: integer, minimum: 1, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 100, default: 10 }
      responses:
        '200':
          description: Lista paginada de notificaciones leídas
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagina: { type: integer }
                  perPage: { type: integer }
                  totalColecciones: { type: integer }
                  totalPaginas: { type: integer }
                  data:
                    type: array
                    items: { $ref: '#/components/schemas/Notificacion' }

  /notificaciones/{id}/read:
    patch:
      summary: Marcar notificación como leída
      tags: [Notificaciones]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Notificación marcada como leída
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  notificacion:
                    $ref: '#/components/schemas/Notificacion'
        '400':
          description: Error en la solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }

components:
  schemas:
    Usuario:
      type: object
      properties:
        id: { type: string }
        nombre: { type: string }
        email: { type: string }
        telefono: { type: string }

    Producto:
      type: object
      properties:
        id: { type: string }
        vendedor: { $ref: '#/components/schemas/Usuario' }
        titulo: { type: string }
        descripcion: { type: string }
        categorias:
          type: array
          items: { type: string }
        precio: { type: number }
        moneda: { type: string }
        stock: { type: integer }
        fotos:
          type: array
          items: { type: string }
        activo: { type: boolean }

    ProductoCrear:
      type: object
      required: [titulo, precio, vendedorId]
      properties:
        titulo: { type: string }
        descripcion: { type: string }
        categorias:
          type: array
          items: { type: string }
        precio: { type: number }
        moneda: { type: string }
        stock: { type: integer }
        vendedorId: { type: string }
        fotos:
          type: array
          items: { type: string }

    ItemPedido:
      type: object
      properties:
        productoId: { type: string }
        cantidad: { type: integer }
        precioUnitario: { type: number }

    DireccionEntrega:
      type: object
      properties:
        calle: { type: string }
        altura: { type: integer }
        piso: { type: string }
        departamento: { type: string }
        codPostal: { type: string }
        ciudad: { type: string }
        provincia: { type: string }
        pais: { type: string }
        lat: { type: number }
        lon: { type: number }

    HistorialEstado:
      type: object
      properties:
        fecha: { type: string, format: date-time }
        estado: 
          type: string
          enum: [PENDIENTE, CONFIRMADO, EN_PREPARACION, ENVIADO, ENTREGADO, CANCELADO]
        quien: { type: string }
        motivo: { type: string }

    Pedido:
      type: object
      properties:
        id: { type: string }
        compradorId: { type: string }
        estado: 
          type: string
          enum: [PENDIENTE, CONFIRMADO, EN_PREPARACION, ENVIADO, ENTREGADO, CANCELADO]
        items:
          type: array
          items: { $ref: '#/components/schemas/ItemPedido' }
        moneda: { type: string }
        direccionEntrega: { $ref: '#/components/schemas/DireccionEntrega' }
        historialEstados:
          type: array
          items: { $ref: '#/components/schemas/HistorialEstado' }
        fechaCreacion: { type: string, format: date-time }
        total: { type: number }

    PedidoResumido:
      type: object
      properties:
        id: { type: string }
        compradorId: { type: string }
        estado: 
          type: string
          enum: [PENDIENTE, CONFIRMADO, EN_PREPARACION, ENVIADO, ENTREGADO, CANCELADO]
        items:
          type: array
          items:
            type: object
            properties:
              productoId: { type: string }
              cantidad: { type: integer }
              precioUnitario: { type: number }

    PedidoCrear:
      type: object
      required: [compradorId, items, moneda, direccionEntrega]
      properties:
        compradorId: { type: string }
        items:
          type: array
          items: { $ref: '#/components/schemas/ItemPedido' }
        moneda: { type: string }
        direccionEntrega: { $ref: '#/components/schemas/DireccionEntrega' }

    Notificacion:
      type: object
      properties:
        id: { type: string }
        usuarioId: { type: string }
        titulo: { type: string }
        mensaje: { type: string }
        tipo: { type: string, enum: [pedido, producto, envio, sistema] }
        leida: { type: boolean }
        fechaCreacion: { type: string, format: date-time }
        fechaLectura: { type: string, format: date-time, nullable: true }